{{- if .Values.db.superUser.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.db.name }}-superuser-esos
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: csg-ro
    kind: SecretStore
  target:
    name: {{ .Values.db.name }}-superuser
    #type: kubernetes.io/basic-auth
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.db.superUser.secretPath }}
        property: {{ .Values.db.superUser.passwordKey }}
{{- end }}
